import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "sonner";
import ConvexClientProvider from "./ConvexClientProvider";
export const metadata: Metadata = {
  title: "Tài Văn Xỉu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Toaster
          toastOptions={{
            style: {
              backgroundImage: `linear-gradient(
                                        122deg,
                                        #8C6339 0.01%,
                                        #C9AF86 49.9%,
                                        #8C6339 100%
                                      )`,
              border: "0px",
            },
          }}
        />
        <body className={inter.className}>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
